// Generated by CoffeeScript 1.9.3
(function() {
  var ajaxObjectClassDataStore, ajaxUtilities;

  ajaxUtilities = require('./ajaxUtilities');

  ajaxObjectClassDataStore = {
    moduleName: "ajaxObjectClassDataStore",
    ajax: function() {
      return {
        get: function(path, args) {
          return ajaxUtilities.httpRequest('GET', path, args, true);
        },
        post: function(path, args) {
          return ajaxUtilities.httpRequest('POST', path, args, true);
        },
        put: function(path, args) {
          return ajaxUtilities.httpRequest('PUT', path, args);
        },
        "delete": function(path, args) {
          return ajaxUtilities.httpRequest('DELETE', path, args);
        }
      };
    },
    all: function() {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/index');
    },
    find: function(id) {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/' + id);
    },
    findBy: function(opts) {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/show', opts);
    },
    where: function(opts) {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/index', opts);
    },
    create: function(opts) {
      return this.ajax.post('/api/' + this.name.toLowerCase + '/new', opts);
    },
    update: function(id, opts) {
      return this.ajax.put('/api/' + this.name.toLowerCase + '/' + id + '/edit', opts);
    }
  };

  module.exports = ajaxObjectClassDataStore;

}).call(this);
