// Generated by CoffeeScript 1.9.3
(function() {
  var AJAXClassMethods, Promise, httpRequest;

  Promise = require('promise');

  httpRequest = function(method, url, args, isJson) {
    return new Promise(function(resolve, reject) {
      var client, uri;
      client = new XMLHttpRequest;
      uri = url;
      if (args) {
        uri += '?';
        uri += _utilities.objectToQueryString(args);
      }
      console.log("Ajax request to " + uri);
      client.open(method, uri);
      client.send();
      client.onload = function() {
        if (this.status === 200) {
          if (isJson) {
            return resolve(JSON.parse(this.response));
          } else {
            return resolve(this.response);
          }
        } else {
          return reject(this.statusText);
        }
      };
      return client.onerror = function() {
        return reject(this.statusText);
      };
    });
  };

  AJAXClassMethods = {
    moduleName: "AJAXClassMethods",
    ajax: function() {
      return {
        get: function(path, args) {
          return httpRequest('GET', path, args, true);
        },
        post: function(path, args) {
          return httpRequest('POST', path, args);
        },
        put: function(path, args) {
          return httpRequest('PUT', path, args);
        },
        "delete": function(path, args) {
          return httpRequest('DELETE', path, args);
        }
      };
    },
    all: function() {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/index');
    },
    find: function(id) {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/' + id);
    },
    findBy: function(opts) {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/show', opts);
    },
    where: function(opts) {
      return this.ajax.get('/api/' + this.name.toLowerCase + '/index', opts);
    },
    create: function(opts) {
      return this.ajax.post('/api/' + this.name.toLowerCase + '/new', opts);
    },
    update: function(id, opts) {
      return this.ajax.put('/api/' + this.name.toLowerCase + '/' + id + '/edit', opts);
    }
  };

  module.exports = AJAXClassMethods;

}).call(this);
