// Generated by CoffeeScript 1.9.3
(function() {
  var _, ajaxObjectClassDataStore, ajaxUtilities;

  _ = require('lodash');

  ajaxUtilities = require('./ajaxUtilities');

  ajaxObjectClassDataStore = {
    moduleName: "ajaxObjectClassDataStore",
    ajax: {
      get: function(path, args) {
        return ajaxUtilities.httpRequest('GET', path, args, true);
      },
      post: function(path, args) {
        return ajaxUtilities.httpRequest('POST', path, args, true);
      },
      put: function(path, args) {
        return ajaxUtilities.httpRequest('PUT', path, args);
      },
      "delete": function(path, args) {
        return ajaxUtilities.httpRequest('DELETE', path, args);
      }
    },
    all: function() {
      return this.ajax.get('/api/' + _.kebabCase(this.name) + '/index');
    },
    find: function(id) {
      return this.ajax.get('/api/' + _.kebabCase(this.name) + '/' + id);
    },
    findBy: function(opts) {
      return this.ajax.get('/api/' + _.kebabCase(this.name) + '/show', opts);
    },
    where: function(opts) {
      return this.ajax.get('/api/' + _.kebabCase(this.name) + '/index', opts);
    },
    create: function(opts) {
      return this.ajax.post('/api/' + _.kebabCase(this.name) + '/new', opts);
    },
    update: function(id, opts) {
      return this.ajax.put('/api/' + _.kebabCase(this.name) + '/' + id + '/edit', opts);
    }
  };

  module.exports = ajaxObjectClassDataStore;

}).call(this);
