// Generated by CoffeeScript 1.9.3
var Base, ClientObject, ajaxObjectClassDataStore, ajaxObjectInstanceDataStore,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Base = require('./Base');

ajaxObjectInstanceDataStore = require('../privateModules/ajaxObjectInstanceDataStore');

ajaxObjectClassDataStore = require('../privateModules/ajaxObjectClassDataStore');

ClientObject = (function(superClass) {
  extend(ClientObject, superClass);

  function ClientObject() {
    return ClientObject.__super__.constructor.apply(this, arguments);
  }

  ClientObject.include(ajaxObjectInstanceDataStore);

  ClientObject.extend(ajaxObjectClassDataStore);

  return ClientObject;

})(Base);

module.exports = ClientObject;
