// Generated by CoffeeScript 1.9.3
var Base, ServerObject, redisObjectClassDataStore, redisObjectInstanceDataStore,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Base = require('./Base');

redisObjectInstanceDataStore = require('../privateModules/redisObjectInstanceDataStore');

redisObjectClassDataStore = require('../privateModules/redisObjectClassDataStore');

ServerObject = (function(superClass) {
  extend(ServerObject, superClass);

  function ServerObject() {
    return ServerObject.__super__.constructor.apply(this, arguments);
  }

  ServerObject.include(redisObjectInstanceDataStore);

  ServerObject.extend(redisObjectClassDataStore);

  return ServerObject;

})(Base);

module.exports = ServerObject;
