// Generated by CoffeeScript 1.9.3
(function() {
  var oomph, publishSubscribe, utilities, validate;

  utilities = require('./utilities');

  publishSubscribe = require('./publishSubscribe');

  validate = require('./validate');

  oomph = {
    utilities: utilities,
    publishSubscribe: publishSubscribe,
    validate: validate,
    createClass: function(name, args) {
      var _class, property;
      _class = function() {
        this.name = name;
        this.initialize.apply(this, arguments);
      };
      if (this.adaptor) {
        _class = this.adaptor.addObjectDataMappingToClass(_class);
      }
      for (property in args) {
        _class.prototype[property] = args[property];
      }
      if (!_class.prototype.initialize) {
        _class.prototype.initialize = function() {};
      }
      _class.extendClass = function(_extendedClass) {
        Object.keys(_extendedClass).forEach((function(_this) {
          return function(key) {
            return _class[key].apply(_this, arguments);
          };
        })(this));
        return Object.keys(_extendedClass.prototype).forEach((function(_this) {
          return function(key) {
            return _class.prototype[key].apply(_this, arguments);
          };
        })(this));
      };
      return _class;
    }
  };

  module.exports = oomph;

}).call(this);
