// Generated by CoffeeScript 1.9.3
(function() {
  var Engine, Part,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Engine = (function(superClass) {
    extend(Engine, superClass);

    function Engine() {
      return Engine.__super__.constructor.apply(this, arguments);
    }

    Engine.defineFields({
      manufacturingId: {
        dataType: 'string',
        identifiable: true,
        sortable: true,
        validates: {
          presence: true,
          uniqueness: true
        }
      },
      modelSpec: {
        dataType: 'reference',
        referenceModelName: 'ModelSpec'
      },
      horsePower: {
        dataType: 'integer'
      },
      parts: {
        dataType: 'reference',
        many: true,
        referenceModelName: 'Part',
        preload: true
      },
      accessories: {
        dataType: 'reference',
        referenceModelName: 'Accessory',
        many: true
      }
    });

    return Engine;

  })(ObjectOrientedModel);

  Part = (function(superClass) {
    extend(Part, superClass);

    function Part() {
      return Part.__super__.constructor.apply(this, arguments);
    }

    Part.defineFields({
      engines: {
        dataType: 'reference',
        many: true
      },
      classification: {
        dataType: 'string',
        searchable: true,
        validates: {
          format: /\w\w\w\d\d/
        }
      }
    });

    return Part;

  })(ObjectOrientedModel);

}).call(this);
